[Master] 

log_file = 'logs/{}_main_run.log'

sql_database = 'databases/COMAP_manchester.db'

pipeline = [#'modules.ProcessLevel2.CreateLevel2File.CreateRebinnedLevel1File.CreateRebinnedLevel1File()',
            'modules.ProcessLevel2.CreateLevel2File.CheckLevel1FileExists.CheckLevel1FileExists()',
            'modules.ProcessLevel2.CreateLevel2File.CreateLevel2File.CreateLevel2File()',
            'modules.ProcessLevel2.SystemTemperature.SystemTemperature.SystemTemperature()',
            'modules.ProcessLevel2.FindScans.FindScans.FindScans()',
            'modules.ProcessLevel2.NoiseStats.NoiseStats.NoiseStatsLevel1()',
            'modules.ProcessLevel2.Atmosphere.Atmosphere.AtmosphereInObservation()',
            'modules.ProcessLevel2.GainFilterAndBin.GainFilterAndBin.GainFilterAndBin()',
            'modules.ProcessLevel2.NoiseStats.NoiseStats.NoiseStatsLevel2()']

nprocess = 4

#source = 'Field7%%' # Use Field15% for all Field150 to 159, for example. 
source_group = 'Galactic'

[modules.ProcessLevel2.CreateLevel2File.CheckLevel1FileExists.CheckLevel1FileExists]

dummy = false

[modules.ProcessLevel2.CreateLevel2File.CreateRebinnedLevel1File.CreateRebinnedLevel1File]

output_dir = '/scratch/nas_core2/sharper/COMAP/data_level1_rebinned/'

[modules.ProcessLevel2.FindScans.FindScans.FindScans]

overwrite = true
plot = false

[modules.ProcessLevel2.Atmosphere.Atmosphere.AtmosphereInObservation]

plot = false
overwrite = false

[modules.ProcessLevel2.NoiseStats.NoiseStats.NoiseStatsLevel1]

plot = false 

[modules.ProcessLevel2.NoiseStats.NoiseStats.NoiseStatsLevel2]

plot = false
overwrite = false 
target_tod_datasets=['level2/binned_filtered_data','level2/binned_data']

[modules.ProcessLevel2.SystemTemperature.SystemTemperature.SystemTemperature]

plot_vane = false 
plot_tsys = false 
plot_dir = 'outputs/plots/SystemTemperature/'
overwrite = false

[modules.ProcessLevel2.CreateLevel2File.CreateLevel2File.CreateLevel2File]

output_dir = '/scratch/nas_core2/sharper/COMAP/level2_data_2024/'

save_dir_structure = '%Y-%m/{source}/level2/'

# Copy this level1 data to the level 2 file
level1_attributes = ['comap'] 
level1_datasets = [['/spectrometer/MJD','1'],
                ['/spectrometer/bands','1'],
                ['/spectrometer/frequency','1'],
                ['/spectrometer/feeds','1'],
                ['/spectrometer/pixel_pointing/pixel_az','1'],
                ['/spectrometer/pixel_pointing/pixel_el','1'],
                ['/spectrometer/pixel_pointing/pixel_ra','1'],
                ['/spectrometer/pixel_pointing/pixel_dec','1'],
                ['/spectrometer/pixel_pointing/pixel_xoffset','1'],
                ['/spectrometer/pixel_pointing/pixel_yoffset','1'],
                ['/hk/antenna0/vane/Tvane','0.01'],
                    ['/hk/antenna0/vane/angle','0.01'],
                    ['/hk/antenna0/vane/Tambient','0.01'],
                    ['/hk/antenna0/vane/Tshroud','0.01'],
                    ['/hk/antenna0/vane/utc', '1'],
                    ['/hk/array/frame/features','1'],
                    ['/hk/array/weather/airTemperature','0.01'],
                    ['/hk/array/weather/pressure','0.01'], 
                    ['/hk/array/weather/dewPointTemp','0.01'],
                    ['/hk/array/weather/windSpeed','0.01'],
                    ['/hk/array/weather/windDirection','0.01']]

[modules.ProcessLevel2.GainFilterAndBin.GainFilterAndBin.GainFilterAndBin]

n_freq_bin = 2
overwrite = false